import "dotenv/config";

export const ENV = {
  PORT: process.env.PORT || 5001,
  NAVER_CLIENT_ID: process.env.NAVER_CLIENT_ID,
  NAVER_CLIENT_SECRET: process.env.NAVER_CLIENT_SECRET,
  NAVER_CLIENT_LOCAL_ID: process.env.NAVER_CLIENT_LOCAL_ID,
  NAVER_CLIENT_LOCAL_SECRET: process.env.NAVER_CLIENT_LOCAL_SECRET,
  GOOGLE_MAPS_API_KEY: process.env.GOOGLE_MAPS_API_KEY,
};
